embed_assets: on

javascripts:
  book:
    - public/javascripts/application.js
    - public/javascripts/models/book.js
    - public/javascripts/views/index.js
    - public/javascripts/controllers/books.js